stages:
  - deploy

.common: &common
  tags: [ "runner:main", "size:large" ]

deploy_to_reliability_env:
  stage: deploy
  when: on_success
  trigger:
    project: DataDog/apm-reliability/datadog-reliability-env
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PROJECT_NAME: $CI_PROJECT_NAME
    UPSTREAM_COMMIT_SHA: $CI_COMMIT_SHA
    FORCE_TRIGGER: $FORCE_TRIGGER

deploy_to_docker_registries:
  stage: deploy
  when: on_success
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: ghcr.io/datadog/dd-trace-js/dd-lib-js-init:v3.2.0
    IMG_DESTINATIONS: dd-lib-js-init:v3.2.0
    IMG_SIGNING: "false"
